apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "toldyouso.fullname" . }}-config
  labels:
    {{- include "toldyouso.labels" . | nindent 4 }}
data:
  toldyouso.properties: |
    {{- range $key, $value := .Values.appConfig }}
    {{ $key }}={{ $value }}
    {{- end }}
  redisson.yaml: |
    codec: !<org.redisson.codec.SerializationCodec> {}
    singleServerConfig:
      address: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
      connectionMinimumIdleSize: 2
      connectionPoolSize: 8
